#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send " cpu users" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send " cpu temperature" "\- shows cpu temperature
- left-click to show intensive processes" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

sensors | awk '/Core 0/ {print "[" $3 "]"}'
