#!/bin/bash

case $BLOCK_BUTTON in
    1) input="$(cat ~/Notes/bujo/todo.md | sed 's/-//')"
        current_block=""
        summary=" todo"
        in_block=false
        notify-send " today" "$(remind -nb1 ~/Notes/calendar.rem | grep $(date +"%Y/%m/%d") | sed 's/^...........//' | sort)" &&
                while IFS= read -r line;
                do
                    if [[ "$line" =~ ^# ]]; then
                        notify-send "$summary" "$current_block"
                        current_block=""
                        summary="$(echo $line | sed 's/# //')"
                    else
                        current_block+="$line\n"
                    fi
                done <<< "$input"
                notify-send "$summary" "$current_block"
                ;;
	3) notify-send " time/date" "\- displays time and date
\- left click to show schedule for current day using remind and to-do list" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

date "+[%Y %b %d (%a) %H:%M]"
