#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send " today" "$(remind -nb1 ~/Notes/calendar.rem | grep $(date +"%Y/%m/%d") | sed 's/^...........//' | sort)" &&
        notify-send " to-do" "$(cat ~/Notes/bujo/todo.md | sed 's/-//')" ;;
	3) notify-send " time/date" "\- displays time and date
\- left click to show schedule for current day using remind and to-do list" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

date "+[%Y %b %d (%a) %H:%M]"
