#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send " Month" "$(cal | sed "s/\<$(date +'%e')\>/<b><span color='red'>&<\/span><\/b>/")" &&
        notify-send " Today" "$(remind -nb1 ~/Notes/calendar.rem | grep $(date +"%Y/%m/%d") | sed 's/^...........//' | sort)" ;;
	3) notify-send " Time/date module" "\- Left click to show schedule for current day using \`remind\` and show the month via \`cal\`." ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

date "+[%Y %b %d (%a) %H:%M]"
