#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send " memory users" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	3) notify-send " memory status" "\- shows memory used/total
- left click to show memory users" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

free --mebi | sed -n '2{p;q}' | awk '{printf ("[%2.2f/%2.2fGiB]\n", ( $3 / 1024), ($2 / 1024))}'
